#!/bin/sh
# Copyright (C) 2009-2016  EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

cat >make-exe << END
P actions make_exec
P actions make_cmde
P version $2
P nomjob forma01a
P ncpus 1
A memjeveux 4.000000
P mem_aster 100
A tpmax 60
P memjob 32768
P mpi_nbcpu 1
P mpi_nbnoeud 1
P tpsjob 1
P mode batch
P soumbtc oui
P consbtc oui

R f ${PWD}/src D 0
F exec ${PWD}/aster.exe DR 0
F conf ${PWD}/config.txt D 0
R capy ${PWD}/catalo D 0
R cmde ${PWD}/commande DR 0
END

$1/bin/as_run  make-exe
