#!/bin/sh
# Copyright (C) 2009-2016  EDF R&D
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# See http://www.salome-platform.org/ or email : webmaster.salome@opencascade.com
#

cat >make-cmd << END
P debug nodebug
P mode interactif
P version $2
P ncpus 1
A args
A memjeveux 16.0
A tpmax 300
P facmtps 1
P corefilesize unlimited
R capy ${PWD}/catalo D 0
R cmde ${PWD}/commande DR 0
P consbtc oui
P soumbtc oui
P actions make_cmde
END


$1 make-cmd
