
include ../makefile.inc

prog:prog.cxx
	g++ -o prog prog.cxx -L./install/lib/salome -lcompo1Exelib
clean:
	rm -rf *.o prog install install.bak appli appli.bak cppcompos_SRC cppcompos_SRC.bak compo1_inst_1 traceExec_proc
