
KERNEL_ROOT_DIR=/local/cchris/Salome/Install/KERNEL_V5

ASTER_ROOT=/local/cchris/Aster/V10.1/aster
ASTER_VERSION=STA10.1
#ASTER_ROOT=/local/cchris/Aster/V10/Install
#ASTER_VERSION=STA10.0

FC=gfortran
